version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.7
  shellcheck: circleci/shellcheck@3.2.0

x-aliases:
  docker-publish-args: &docker-publish-args
    requires:
      - shellcheck/check
    registry: $DOCKER_REGISTRY
    image: $DOCKER_IMAGE
    after_build:
      - run:
          name: Test generated image
          command: ./test.sh
  filter-only-develop: &filter-only-develop
    filters:
      branches:
        only:
          - develop
  filter-only-master: &filter-only-master
    filters:
      branches:
        only:
          - master
  filter-except-main: &filter-except-main
    filters:
      branches:
        ignore:
          - develop
          - master
  filter-only-tagged: &filter-only-tagged
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /.*/
  filter-branch-or-tagged: &filter-branch-or-tagged
    filters:
      tags:
        only:
          - /.*/

workflows:
  version: 2
  build:
    jobs:
      - shellcheck/check:
          <<: *filter-branch-or-tagged
          pre-steps:
            - run:
                name: "Install git and SSH client"
                command: |
                  apk add \
                      --update-cache \
                      --no-progress \
                      git \
                      openssh-client
      - docker-publish/publish:
          name: docker-build-branch
          <<: *docker-publish-args
          <<: *filter-except-main
          deploy: false
      - docker-publish/publish:
          name: docker-build-and-publish-develop
          <<: *docker-publish-args
          <<: *filter-only-develop
          tag: edge
      - docker-publish/publish:
          name: docker-build-and-publish-master
          <<: *docker-publish-args
          <<: *filter-only-master
          tag: latest
      - docker-publish/publish:
          name: docker-build-and-publish-release
          <<: *docker-publish-args
          <<: *filter-only-tagged
          tag: $CIRCLE_TAG
